packages:
  - apps/*
  - scripts

autoInstallPeers: false

catalog:
  '@types/node': ^25.3.3
  framer-motion: ^12.38.0
  lucide-react: ^0.545.0
  tailwindcss: ^4.2.2
  tsx: ^4.21.0

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - msw
  - unrs-resolver

overrides:
  '@esbuild-kit/esm-loader': npm:tsx@^4.21.0
  esbuild: 0.27.3
